build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.20
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  armv7: ghcr.io/home-assistant/armv7-base:3.20
args:
  amd64:
    BUILD_ARCH: amd64
  aarch64:
    BUILD_ARCH: aarch64
  armv7:
    BUILD_ARCH: armv7
