build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
args:
  VECTOR_VERSION: "0.39.0"
  BUILD_ARCH: ${ARCH}

